### ISSUE TITLE
encodeABI is not a function 

### ISSUE THREAD

**Issue by dsslimshaddy** [trufflesuite/truffle-contract#98]
This works in web3 1.0 api
```
const Contract = new web3Instance.eth.Contract(artifacts.abi);
Contract.methods.myfunc().encodeABI()

```

but this does not works in truffle-contract

```
conts Contract = contract(artifacts);
var instance = await Contract.deployed();
instance.myfunc().encodeABI(); // encodeABI not a func
```

**Comment by cgewecke** [comment]
@dsslimshaddy Thank for noting this. `truffle-contract` currently uses `web3 0.20.x`. There's ongoing work at #95 to migrate the module to Web3 1.0. Closing as duplicate of #56.
